// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUxs-UF_XBnwiIdw17MWDUQzjEacKrLpg',
    appId: '1:552712818556:web:9be28e511c85e82ed59ef9',
    messagingSenderId: '552712818556',
    projectId: 'ultra-bearing-402000',
    authDomain: 'ultra-bearing-402000.firebaseapp.com',
    storageBucket: 'ultra-bearing-402000.appspot.com',
    measurementId: 'G-DBH8D56ZEL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDmHp4H9lkOVOoVwh3-ml6ouflDPextb0',
    appId: '1:552712818556:android:aced6cea57e42e02d59ef9',
    messagingSenderId: '552712818556',
    projectId: 'ultra-bearing-402000',
    storageBucket: 'ultra-bearing-402000.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiMU1TEKjxIvQ1S2K_9fxs-1stMoRIc84',
    appId: '1:552712818556:ios:7e9d9f7c1a896242d59ef9',
    messagingSenderId: '552712818556',
    projectId: 'ultra-bearing-402000',
    storageBucket: 'ultra-bearing-402000.appspot.com',
    iosBundleId: 'com.example.shopease',
  );
}
